Repository CA-G12/brands-team-7, pull requests merged in 2022-08, with the labels that each got.

#8 build file strcture
  .eslintrc.json
  .gitignore
  client/index.html
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/databse/build.sql
  server/databse/config/connection.js
  server/databse/queries/query.js
  server/index.js
  server/router.js
Labels: done

#12 Heuoku database
  package-lock.json
  package.json
  server/controllers/dataPost.js
  server/controllers/index.js
  server/databse/config/build.js
  server/databse/config/connection.js
  server/databse/queries/index.js
  server/databse/queries/postData.js
  server/router.js
  tests/databaseTests.test.js
Labels: waiting review

#13 fixeting
  server/databse/config/connection.js
Labels: done

#14 edit
  server/databse/config/connection.js
Labels: done

#16 send products
  client/dom.js
  client/index.html
  server/app.js
  server/controllers/getData.js
  server/controllers/index.js
  server/databse/queries/index.js
  server/databse/queries/query.js
  server/router.js
Labels: waiting review

#18 add products to database
  client/dom.js
  server/controllers/dataPost.js
  server/controllers/index.js
  server/databse/config/connection.js
  server/databse/queries/index.js
  server/databse/queries/postData.js
  server/router.js
Labels: waiting

#20 Creating the DOM
  client/dom.js
  client/index.html
  server/controllers/dataPost.js
  server/controllers/getProducts.js
  server/controllers/index.js
  server/databse/queries/getProductId.js
  server/databse/queries/index.js
  server/databse/queries/products.js
  server/router.js
Labels: waiting review

#21 adding database tests
  server/databse/config/build.js
  tests/databaseTests.test.js
Labels: waiting review

#24 add readme
  README.md
Labels: waiting review
